[package]
name = "twitcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
crossbeam = "0.8.4"
crossterm = "0.28.1"
reqwest = "0.12.12"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
